services:
  santa:
    build: .
    command: python -u DockerChristmasPubSub/santa.py #DockerChristmasPubSub/DockerChristmasDealerRouter

  reindeer:
    build: .
    command: python -u DockerChristmasPubSub/reindeer.py #DockerChristmasPubSub/DockerChristmasDealerRouter
    deploy:
      replicas: 9

  elf:
    build: .
    command: python -u DockerChristmasPubSub/elf.py #DockerChristmasPubSub/DockerChristmasDealerRouter
    deploy:
      replicas: 8